// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Heroesprofile.Uploader.Common;
//
//    var uploadResult = UploadResult.FromJson(jsonString);

namespace Heroesprofile.Uploader.Common
{
    using System;

    using System.Globalization;
    using System.Text.Json;
    using System.Text.Json.Serialization;

    public partial class UploadResult
    {
        [JsonPropertyName("fingerprint")]
        public Guid Fingerprint { get; set; }

        [JsonPropertyName("replayID")]
        public int ReplayId { get; set; }

        [JsonPropertyName("status")]
        public string Status { get; set; }
    }

    public partial class UploadResult
    {
        public static UploadResult FromJson(string json) => JsonSerializer.Deserialize<UploadResult>(json, Heroesprofile.Uploader.Common.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this UploadResult self) => JsonSerializer.Serialize(self, Heroesprofile.Uploader.Common.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new JsonSerializerOptions {

            Converters = { 
                new IsoDateTimeConverter(DateTimeStyles.AssumeUniversal)
            },
        };
    }
}
